## Demo: Collecting tweets for a user

Fetching tweets for a particular user by using twarc's <code>timeline</code> command.

In [3]:
!twarc timeline rajapintaco > rajapinta-user-tweets.jsonl

In [4]:
!ls

Compare-outputs.ipynb       rajapinta-twarc.jsonl
LICENSE                     rajapinta-twarc.xlsx
README.md                   rajapinta-tweets.jsonl
Twarc-demo.ipynb            rajapinta-user-tweets.jsonl
Untitled.ipynb              rajapinta.csv
data                        rajapinta.jsonl
env                         rajapinta.xlsx
fetchTweets.R               twarc.log

In [7]:
import json

with open('rajapinta-user-tweets.jsonl') as f:
    tweets_jsonl = f.read()
    
tweets = [json.loads(jline) for jline in tweets_jsonl.splitlines()]

In [9]:
import pandas as pd

In [10]:
df = pd.DataFrame(tweets)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 334 entries, 0 to 333
Data columns (total 31 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   created_at                 334 non-null    object
 1   id                         334 non-null    int64
 2   id_str                     334 non-null    object
 3   full_text                  334 non-null    object
 4   truncated                  334 non-null    bool
 5   display_text_range         334 non-null    object
 6   entities                   334 non-null    object
 7   source                     334 non-null    object
 8   in_reply_to_status_id      6 non-null      float64
 9   in_reply_to_status_id_str  6 non-null      object
 10  in_reply_to_user_id        7 non-null      float64
 11  in_reply_to_user_id_str    7 non-null      object
 12  in_reply_to_screen_name    7 non-null      object
 13  user                       334 non-null    object
 14  geo                        0 non-null      object
 15  coordinates                0 non-null      object
 16  place                      0 non-null      object
 17  contributors               0 non-null      object
 18  is_quote_status            334 non-null    bool
 19  retweet_count              334 non-null    int64
 20  favorite_count             334 non-null    int64
 21  favorited                  334 non-null    bool
 22  retweeted                  334 non-null    bool
 23  lang                       334 non-null    object
 24  possibly_sensitive         250 non-null    object
 25  retweeted_status           68 non-null     object
 26  quoted_status_id           14 non-null     float64
 27  quoted_status_id_str       14 non-null     object
 28  quoted_status_permalink    14 non-null     object
 29  extended_entities          87 non-null     object
 30  quoted_status              8 non-null      object
dtypes: bool(4), float64(3), int64(3), object(21)
memory usage: 71.9+ KB

In [11]:
df.head()

,created_at,id,id_str,full_text,truncated,display_text_range,entities,source,in_reply_to_status_id,in_reply_to_status_id_str,...,favorited,retweeted,lang,possibly_sensitive,retweeted_status,quoted_status_id,quoted_status_id_str,quoted_status_permalink,extended_entities,quoted_status
0,Wed Jun 02 07:30:32 +0000 2021,1399991807564521478,1399991807564521478,Hey members! Remember our springtime get-toget...,False,"[0, 103]","{'hashtags': [], 'symbols': [], 'user_mentions...","<a href=""https://about.twitter.com/products/tw...",NaN,None,...,False,False,en,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Fri May 28 12:06:22 +0000 2021,1398249286559744002,1398249286559744002,Rajapinta ja kolme muuta tieteellistä yhdistys...,False,"[0, 157]","{'hashtags': [{'text': 'tutkimus', 'indices': ...","<a href=""https://about.twitter.com/products/tw...",NaN,None,...,False,False,fi,False,NaN,NaN,NaN,NaN,NaN,NaN
2,Mon May 03 05:30:00 +0000 2021,1389089838872334336,1389089838872334336,Today's meetup on content moderation starts at...,False,"[0, 92]","{'hashtags': [], 'symbols': [], 'user_mentions...","<a href=""https://about.twitter.com/products/tw...",NaN,None,...,False,False,en,False,NaN,NaN,NaN,NaN,NaN,NaN
3,Fri Apr 30 06:16:56 +0000 2021,1388014485936431104,1388014485936431104,Lectio praecursoria: The Language of Emotions ...,False,"[0, 69]","{'hashtags': [], 'symbols': [], 'user_mentions...","<a href=""http://publicize.wp.com/"" rel=""nofoll...",NaN,None,...,False,False,en,False,NaN,NaN,NaN,NaN,NaN,NaN
4,Mon Apr 26 13:40:27 +0000 2021,1386676550989451264,1386676550989451264,Moderation meet-up coming up on Monday 3rd of ...,False,"[0, 156]","{'hashtags': [], 'symbols': [], 'user_mentions...","<a href=""https://about.twitter.com/products/tw...",NaN,None,...,False,False,en,False,NaN,NaN,NaN,NaN,NaN,NaN